### PR TITLE
Update install_conda_env.sh

### PR DESCRIPTION
**Pull request by phseidl**
install right openbabel for syscall in smiles.py (to_mol2_file)

### CODE REVIEW

**Comment by kudkudak** [comment]
@cieplinski-tobiasz

**Comment by kudkudak** [comment]
Thanks! We will take a look shortly

**Comment by cieplinski-tobiasz** [comment]
Hi,
Thanks for pointing this out. However, as far as I can see, openbabel from openbabel channel is deprecated -- conda-forge channel is recommended.
Unless there are some problems with using conda-forge that I am not aware of, I'd rather use conda-forge. I'll update the branch accordingly and merge it soon.

**Comment by cieplinski-tobiasz** [comment]
Adapted your fix and pushed it to master and v2.0. Thanks!

**Pull request closed without merging**
